version: '2'
services:

 mysql:
  image: mysql
  container_name: pwcho2018-Nr-83860
  volumes:
   - mysql:/var/lib/mysql
  environment:
   - MYSQL_ROOT_PASSWORD=root
   - MYSQL_DATABASE=LW
   - MYSQL_USER=gagarin
   - MYSQL_PASSWORD=qwe123 
  ports:
   - "3306:3306"
  networks:
   Bridge-Zadanie-1:
    ipv4_address: 10.0.10.3
  

 java:
  image: lukasek09/zadaniesamodzielne
  container_name: java
  depends_on:
   - mysql
  networks:
   - Bridge-Zadanie-1
  external_links:
   - mysql

volumes:
 mysql:
networks:
 Bridge-Zadanie-1:
  driver: bridge
  ipam:
   config:
    - subnet: "10.0.10.0/24"
      gateway: "10.0.10.1"
